#!/bin/bash

. smoke.sh

BASE_URL=${1:-https://democicdapp.herokuapp.com}
smoke_url_prefix "$BASE_URL"
smoke_url_ok "/"
    smoke_assert_body "Demo"

smoke_url "/error"
    smoke_assert_code 500
    smoke_assert_body "err"
smoke_url_ok "/metrics"
    smoke_assert_body "python_gc_collections_total"
smoke_report

